import p1 from "../../assets/Phones/red10.png";
import p2 from "../../assets/Phones/redmi125g.jpg";
import p3 from "../../assets/Phones/redn105g.jpg";
import p4 from "../../assets/Phones/redn105g2.jpg";
import p5 from "../../assets/Phones/apple15.jpg";
import p6 from "../../assets/Phones/google.jpg";
import p7 from "../../assets/Phones/google2.jpg";
import p8 from "../../assets/Phones/i14.png";
import p10 from "../../assets/Phones/moto.jpg";
import p11 from "../../assets/Phones/moto2.jpg";
import p12 from "../../assets/Phones/one12.png";
import p13 from "../../assets/Phones/one121.png";
import p14 from "../../assets/Phones/one122.png";
import p15 from "../../assets/Phones/oneplus-5g.jpg";
import p16 from "../../assets/Phones/oneplus85g.png";
import p17 from "../../assets/Phones/silver.jpg";
import l1 from "../../assets/Laptops/RogStrix.png";
import l2 from "../../assets/Laptops/RogZephyrus.jpg";
import l3 from "../../assets/Laptops/hp14.jpg";
import l4 from "../../assets/Laptops/hp14s.png";
import l5 from "../../assets/Laptops/Asus.png";
import l6 from "../../assets/Laptops/Asus2.jpg";
import l7 from "../../assets/Laptops/asus13.jpg";
import l8 from "../../assets/Laptops/Asusgameing.jpg";
import l9 from "../../assets/Laptops/AsusVivobook.jpg";
import l10 from "../../assets/Laptops/hp.jpg";
import l11 from "../../assets/Laptops/hp2.jpg";
import l12 from "../../assets/Laptops/hp10.jpg";
import l13 from "../../assets/Laptops/hp14.jpg";
import l14 from "../../assets/Laptops/Hp15.webp";
import w1 from "../../assets/Watchs/Smartwatch.jpg";
import w2 from "../../assets/Watchs/sonata.jpg";
import w3 from "../../assets/Watchs/sonata2.jpg";
import w4 from "../../assets/Watchs/Titan.jpg";
import w5 from "../../assets/Watchs/Titan2.jpg";
import w6 from "../../assets/Watchs/wristwatch.jpg";
import w7 from "../../assets/Watchs/SoneplusWatch.png";
import w8 from "../../assets/Watchs/SoneplusWatch2.png";

const ProductDetails = {
  Phones: [
    {
      name: "Redmi 10",
      ram: "8GB",
      storage: "128GB",
      color: "Titan Black",
      price: 22999,
      originalPrice: 28999,
      rating: 4,
      delivery: "Wed, 30th Jul",
      image: p1,
      subtitle: "5000MAH  || BATTARY",
      discount: 4000,
      images: [p1, p2, p3],
      reviewsCount: 1000,
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi suscipit minima autem quibusdam dignissimos consectetur velit praesentium dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi",
    },
    {
      name: "Redmi 12 5G",
      ram: "8GB",
      storage: "128GB",
      color: "Black",
      price: 22999,
      originalPrice: 28999,
      rating: 3,
      delivery: "Wed, 30th Jul",
      image: p2,
      subtitle: "5000MAH  || BATTARY",
      discount: 4000,
      images: [p1, p2, p3],
      reviewsCount: 1000,
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi suscipit minima autem quibusdam dignissimos consectetur velit praesentium dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi",
    },
    {
      name: "Redmi Note 10 5G",
      ram: "8GB",
      storage: "128GB",
      color: "White",
      price: 22999,
      originalPrice: 28999,
      rating: 5,
      delivery: "Wed, 30th Jul",
      image: p3,
      subtitle: "5000MAH  || BATTARY",
      discount: 4000,
      images: [p1, p2, p3],
      reviewsCount: 1000,
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi suscipit minima autem quibusdam dignissimos consectetur velit praesentium dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi",
    },
    {
      name: "Redmi Note 10 5G",
      ram: "8GB",
      storage: "128GB",
      color: "Sky Blue",
      price: 22999,
      originalPrice: 28999,
      rating: Math.floor(Math.random() * 5) + 1,
      delivery: "Wed, 30th Jul",
      image: p4,
      subtitle: "5000MAH  || BATTARY",
      discount: 4000,
      images: [p1, p2, p3],
      reviewsCount: 1000,
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi suscipit minima autem quibusdam dignissimos consectetur velit praesentium dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi",
    },
    {
      name: "Iphone 15",
      ram: "8GB",
      storage: "128GB",
      color: "Pink",
      price: 22999,
      originalPrice: 28999,
      rating: Math.floor(Math.random() * 5) + 1,
      delivery: "Wed, 30th Jul",
      image: p5,
       subtitle: "5000MAH  || BATTARY",
      discount: 4000,
      images: [p1, p2, p3],
      reviewsCount: 1000,
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi suscipit minima autem quibusdam dignissimos consectetur velit praesentium dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi",
    },
    {
      name: "Google",
      ram: "8GB",
      storage: "128GB",
      color: "Blue",
      price: 22999,
      originalPrice: 28999,
      rating: Math.floor(Math.random() * 5) + 1,
      delivery: "Wed, 30th Jul",
      image: p6,
       subtitle: "5000MAH  || BATTARY",
      discount: 4000,
      images: [p1, p2, p3],
      reviewsCount: 1000,
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi suscipit minima autem quibusdam dignissimos consectetur velit praesentium dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi",
    },
    {
      name: "Google",
      ram: "8GB",
      storage: "128GB",
      color: "Silver with White",
      price: 22999,
      originalPrice: 28999,
      rating: Math.floor(Math.random() * 5) + 1,
      delivery: "Wed, 30th Jul",
      image: p7,
       subtitle: "5000MAH  || BATTARY",
      discount: 4000,
      images: [p1, p2, p3],
      reviewsCount: 1000,
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi suscipit minima autem quibusdam dignissimos consectetur velit praesentium dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi",
    },
    {
      name: "Iphone 14",
      ram: "8GB",
      storage: "128GB",
      color: "Silver with White",
      price: 22999,
      originalPrice: 28999,
      rating: Math.floor(Math.random() * 5) + 1,
      delivery: "Wed, 30th Jul",
      image: p8,
       subtitle: "5000MAH  || BATTARY",
      discount: 4000,
      images: [p1, p2, p3],
      reviewsCount: 1000,
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi suscipit minima autem quibusdam dignissimos consectetur velit praesentium dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi",
    },
    {
      name: "Moto",
      ram: "8GB",
      storage: "128GB",
      color: "Black",
      price: 22999,
      originalPrice: 28999,
      rating: 3,
      delivery: "Wed, 30th Jul",
      image: p10,
       subtitle: "5000MAH  || BATTARY",
      discount: 4000,
      images: [p1, p2, p3],
      reviewsCount: 1000,
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi suscipit minima autem quibusdam dignissimos consectetur velit praesentium dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi",
    },
    {
      name: "Moto",
      ram: "8GB",
      storage: "128GB",
      color: "Sky Blue",
      price: 22999,
      originalPrice: 28999,
      rating: 5,
      delivery: "Wed, 30th Jul",
      image: p11,
       subtitle: "5000MAH  || BATTARY",
      discount: 4000,
      images: [p1, p2, p3],
      reviewsCount: 1000,
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi suscipit minima autem quibusdam dignissimos consectetur velit praesentium dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi",
    },
    {
      name: "Oneplus",
      ram: "8GB",
      storage: "128GB",
      color: "Sky Blue",
      price: 22999,
      originalPrice: 28999,
      rating: Math.floor(Math.random() * 5) + 1,
      delivery: "Wed, 30th Jul",
      image: p12,
       subtitle: "5000MAH  || BATTARY",
      discount: 4000,
      images: [p1, p2, p3],
      reviewsCount: 1000,
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi suscipit minima autem quibusdam dignissimos consectetur velit praesentium dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi",
    },
    {
      name: "Oneplus 5G",
      ram: "8GB",
      storage: "128GB",
      color: "Sky Blue",
      price: 22999,
      originalPrice: 28999,
      rating: Math.floor(Math.random() * 5) + 1,
      delivery: "Wed, 30th Jul",
      image: p13,
       subtitle: "5000MAH  || BATTARY",
      discount: 4000,
      images: [p1, p2, p3],
      reviewsCount: 1000,
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi suscipit minima autem quibusdam dignissimos consectetur velit praesentium dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi",
    },
    {
      name: "Oneplus",
      ram: "8GB",
      storage: "128GB",
      color: "Orange",
      price: 22999,
      originalPrice: 28999,
      rating: Math.floor(Math.random() * 5) + 1,
      delivery: "Wed, 30th Jul",
      image: p14,
       subtitle: "5000MAH  || BATTARY",
      discount: 4000,
      images: [p1, p2, p3],
      reviewsCount: 1000,
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi suscipit minima autem quibusdam dignissimos consectetur velit praesentium dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi",
    },
    {
      name: "Oneplus 5G",
      ram: "8GB",
      storage: "128GB",
      color: "Sky Blue",
      price: 22999,
      originalPrice: 28999,
      rating: Math.floor(Math.random() * 5) + 1,
      delivery: "Wed, 30th Jul",
      image: p15,
       subtitle: "5000MAH  || BATTARY",
      discount: 4000,
      images: [p1, p2, p3],
      reviewsCount: 1000,
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi suscipit minima autem quibusdam dignissimos consectetur velit praesentium dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi",
    },
    {
      name: "Oneplus ",
      ram: "8GB",
      storage: "128GB",
      color: "Black",
      price: 22999,
      originalPrice: 28999,
      rating: Math.floor(Math.random() * 5) + 1,
      delivery: "Wed, 30th Jul",
      image: p16,
       subtitle: "5000MAH  || BATTARY",
      discount: 4000,
      images: [p1, p2, p3],
      reviewsCount: 1000,
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi suscipit minima autem quibusdam dignissimos consectetur velit praesentium dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi",
    },
    {
      name: "Redmi 12 5G",
      ram: "8GB",
      storage: "128GB",
      color: "Silver",
      price: 22999,
      originalPrice: 28999,
      rating: Math.floor(Math.random() * 5) + 1,
      delivery: "Wed, 30th Jul",
      image: p17,
       subtitle: "5000MAH  || BATTARY",
      discount: 4000,
      images: [p1, p2, p3],
      reviewsCount: 1000,
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi suscipit minima autem quibusdam dignissimos consectetur velit praesentium dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi",
    },
  ],
  Laptops: [
    {
      name: "ROG Strix",
      ram: "8GB",
      storage: "128GB",
      color: "Black",
      price: 22999,
      originalPrice: 28999,
      rating: 4,
      delivery: "Wed, 30th Jul",
      image: l1,
      subtitle: "Fast Charging",
      discount: 4000,
      images: [l1, l2, l3],
      reviewsCount: 1000,
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi suscipit minima autem quibusdam dignissimos consectetur velit praesentium dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi",
    },
    {
      name: "ROG Zephyrus",
      ram: "8GB",
      storage: "128GB",
      color: "Black",
      price: 22999,
      originalPrice: 28999,
      rating: 4,
      delivery: "Wed, 30th Jul",
      image: l2,
      subtitle: "Fast Charging",
      discount: 4000,
      images: [l1, l2, l3],
      reviewsCount: 1000,
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi suscipit minima autem quibusdam dignissimos consectetur velit praesentium dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi",
    },
    {
      name: "HP 14",
      ram: "8GB",
      storage: "128GB",
      color: "Black",
      price: 22999,
      originalPrice: 28999,
      rating: 4,
      delivery: "Wed, 30th Jul",
      image: l3,
      subtitle: "Fast Charging",
      discount: 4000,
      images: [l1, l2, l3],
      reviewsCount: 1000,
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi suscipit minima autem quibusdam dignissimos consectetur velit praesentium dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi",
    },
    {
      name: "HP 14 S",
      ram: "8GB",
      storage: "128GB",
      color: "Black",
      price: 22999,
      originalPrice: 28999,
      rating: 4,
      delivery: "Wed, 30th Jul",
      image: l4,
      subtitle: "Fast Charging",
      discount: 4000,
      images: [l1, l2, l3],
      reviewsCount: 1000,
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi suscipit minima autem quibusdam dignissimos consectetur velit praesentium dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi",
    },
    {
      name: "Asus",
      ram: "8GB",
      storage: "128GB",
      color: "Black",
      price: 22999,
      originalPrice: 28999,
      rating: 4,
      delivery: "Wed, 30th Jul",
      image: l5,
      subtitle: "Fast Charging",
      discount: 4000,
      images: [l1, l2, l3],
      reviewsCount: 1000,
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi suscipit minima autem quibusdam dignissimos consectetur velit praesentium dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi",
    },
    {
      name: "Asus",
      ram: "8GB",
      storage: "128GB",
      color: "Black",
      price: 22999,
      originalPrice: 28999,
      rating: 4,
      delivery: "Wed, 30th Jul",
      image: l6,
      subtitle: "Fast Charging",
      discount: 4000,
      images: [l1, l2, l3],
      reviewsCount: 1000,
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi suscipit minima autem quibusdam dignissimos consectetur velit praesentium dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi",
    },
    {
      name: "Asus",
      ram: "8GB",
      storage: "128GB",
      color: "Black",
      price: 22999,
      originalPrice: 28999,
      rating: 4,
      delivery: "Wed, 30th Jul",
      image: l7,
      subtitle: "Fast Charging",
      discount: 4000,
      images: [l1, l2, l3],
      reviewsCount: 1000,
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi suscipit minima autem quibusdam dignissimos consectetur velit praesentium dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi",
    },
    {
      name: "HP 14 S",
      ram: "8GB",
      storage: "128GB",
      color: "Black",
      price: 22999,
      originalPrice: 28999,
      rating: 4,
      delivery: "Wed, 30th Jul",
      image: l8,
      subtitle: "Fast Charging",
      discount: 4000,
      images: [l1, l2, l3],
      reviewsCount: 1000,
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi suscipit minima autem quibusdam dignissimos consectetur velit praesentium dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi",
    },
    {
      name: "HP 14 S",
      ram: "8GB",
      storage: "128GB",
      color: "Black",
      price: 22999,
      originalPrice: 28999,
      rating: 4,
      delivery: "Wed, 30th Jul",
      image: l9,
      subtitle: "Fast Charging",
      discount: 4000,
      images: [l1, l2, l3],
      reviewsCount: 1000,
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi suscipit minima autem quibusdam dignissimos consectetur velit praesentium dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi",
    },
    {
      name: "HP 14 S",
      ram: "8GB",
      storage: "128GB",
      color: "Black",
      price: 22999,
      originalPrice: 28999,
      rating: 4,
      delivery: "Wed, 30th Jul",
      image: l10,
      subtitle: "Fast Charging",
      discount: 4000,
      images: [l1, l2, l3],
      reviewsCount: 1000,
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi suscipit minima autem quibusdam dignissimos consectetur velit praesentium dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi",
    },
    {
      name: "HP 14 S",
      ram: "8GB",
      storage: "128GB",
      color: "Black",
      price: 22999,
      originalPrice: 28999,
      rating: 4,
      delivery: "Wed, 30th Jul",
      image: l11,
      subtitle: "Fast Charging",
      discount: 4000,
      images: [l1, l2, l3],
      reviewsCount: 1000,
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi suscipit minima autem quibusdam dignissimos consectetur velit praesentium dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi",
    },
    {
      name: "HP 14 S",
      ram: "8GB",
      storage: "128GB",
      color: "Black",
      price: 22999,
      originalPrice: 28999,
      rating: 4,
      delivery: "Wed, 30th Jul",
      image: l12,
      subtitle: "Fast Charging",
      discount: 4000,
      images: [l1, l2, l3],
      reviewsCount: 1000,
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi suscipit minima autem quibusdam dignissimos consectetur velit praesentium dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi",
    },
    {
      name: "HP 14 S",
      ram: "8GB",
      storage: "128GB",
      color: "Black",
      price: 22999,
      originalPrice: 28999,
      rating: 4,
      delivery: "Wed, 30th Jul",
      image: l13,
      subtitle: "Fast Charging",
      discount: 4000,
      images: [l1, l2, l3],
      reviewsCount: 1000,
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi suscipit minima autem quibusdam dignissimos consectetur velit praesentium dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi",
    },
    {
      name: "HP 14 S",
      ram: "8GB",
      storage: "128GB",
      color: "Black",
      price: 22999,
      originalPrice: 28999,
      rating: 4,
      delivery: "Wed, 30th Jul",
      image: l14,
      subtitle: "Fast Charging",
      discount: 4000,
      images: [l1, l2, l3],
      reviewsCount: 1000,
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi suscipit minima autem quibusdam dignissimos consectetur velit praesentium dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi",
    }
  ],
  Watches: [
    {
      name: "Smartwatch",
      color: "Black",
      price: 2999,
      originalPrice: 3999,
      rating: 4,
      delivery: "Wed, 30th Jul",
      image: w1,
      subtitle: "Water Proof",
      discount: 4000,
      images: [w1, w2, w3],
      reviewsCount: 1000,
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi suscipit minima autem quibusdam dignissimos consectetur velit praesentium dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi",
    },
    {
      name: "Sonata",
      color: "Gold",
      price: 3999,
      originalPrice: 4999,
      rating: 4,
      delivery: "Wed, 30th Jul",
      image: w2,
      subtitle: "Water Proof",
      discount: 4000,
      images: [w1, w2, w3],
      reviewsCount: 1000,
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi suscipit minima autem quibusdam dignissimos consectetur velit praesentium dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi",
    },
    {
      name: "Sonata",
      color: "Brown with Gold",
      price: 3999,
      originalPrice: 4999,
      rating: 4,
      delivery: "Wed, 30th Jul",
      image: w3,
      subtitle: "Water Proof",
      discount: 4000,
      images: [w1, w2, w3],
      reviewsCount: 1000,
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi suscipit minima autem quibusdam dignissimos consectetur velit praesentium dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi",
    },
    {
      name: "Titan",
      color: "Black",
      price: 2999,
      originalPrice: 5999,
      rating: 4,
      delivery: "Wed, 30th Jul",
      image: w4,
      subtitle: "Water Proof",
      discount: 4000,
      images: [w1, w2, w3],
      reviewsCount: 1000,
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi suscipit minima autem quibusdam dignissimos consectetur velit praesentium dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi",
    },
    {
      name: "Titan",
      color: "Brown With White",
      price: 3999,
      originalPrice: 5999,
      rating: 4,
      delivery: "Wed, 30th Jul",
      image: w5,
      subtitle: "Water Proof",
      discount: 4000,
      images: [w1, w2, w3],
      reviewsCount: 1000,
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi suscipit minima autem quibusdam dignissimos consectetur velit praesentium dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi",
    },
    {
      name: "Wrist Watch",
      color: "Black With Brown",
      price: 2999,
      originalPrice: 4999,
      rating: 4,
      delivery: "Wed, 30th Jul",
      image: w6,
      subtitle: "Water Proof",
      discount: 4000,
      images: [w1, w2, w3],
      reviewsCount: 1000,
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi suscipit minima autem quibusdam dignissimos consectetur velit praesentium dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi",
    },
    {
      name: "Smart Watch Oneplus",
      color: "Gray",
      price: 4999,
      originalPrice: 6999,
      rating: 4,
      delivery: "Wed, 30th Jul",
      image: w7,
      subtitle: "Water Proof",
      discount: 4000,
      images: [w1, w2, w3],
      reviewsCount: 1000,
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi suscipit minima autem quibusdam dignissimos consectetur velit praesentium dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi",
    },
    {
      name: "Smart Watch Oneplus",
      color: "Black",
      price: 5999,
      originalPrice: 7999,
      rating: 4,
      delivery: "Wed, 30th Jul",
      image: w8,
      subtitle: "Water Proof",
      discount: 4000,
      images: [w1, w2, w3],
      reviewsCount: 1000,
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi suscipit minima autem quibusdam dignissimos consectetur velit praesentium dolor sit amet consectetur adipisicing elit. Corrupti voluptatibus maiores tempora sint assumenda atque doloremque ipsam architecto. Voluptas et dolorum animi",
    },
  ],
};
export default ProductDetails;
